### PR TITLE
Cleanup and fix Travis

### PR DESCRIPTION
**Pull request by andrrizzi**
- [x] File cleanup
- [x] Fix travis test
- [x] Add license
- [x] Write better README

### CODE REVIEW

**Comment by jchodera** [comment]
I'm really surprised by the segfault:
```
Doctest: openmmmcmc.states.ThermodynamicState.create_context ... /home/travis/build.sh: line 59:  1603 Segmentation fault      (core dumped) nosetests $PACKAGENAME --nocapture --nologcapture --verbosity=2 --with-doctest
```

**Comment by andrrizzi** [comment]
Me too! Never seen it before. I'll get there too.

**Comment by jchodera** [comment]
Which OpenMM is in use here?

**Comment by andrrizzi** [comment]
Seems to be installing `openmm 7.2`. I'll try to switch to 7.1 and see if it disappear.

**Comment by jchodera** [comment]
They should be nearly identical, so I don't think it's worth it.

Can we try to reproduce this locally?

**Comment by andrrizzi** [comment]
I have run those tests many times locally with openmm 7.1 and never found the error. I'll keep messing with travis a little.

**Comment by andrrizzi** [comment]
@jchodera I think this is ready to be merged. There's still something weird going on with that specific doctest, but I need this PR in today and normal tests pass. I'll try to figure out what's happening there in a different PR.

**Comment by andrrizzi** [comment]
All doctests pass locally, anyway.

**Comment by jchodera** [comment]
Everything looks good! Thanks!

**Pull request merged**
