### PR TITLE
Initial import of repex stuff

### PR DESCRIPTION
**Pull request by pgrinaway**
This is the initial import of repex stuff. I'm doing it as a PR so that we can make sure that names are ok and the right tests have been brought in. Still migrating stuff/fixing minor things like print statements...

### CODE REVIEW

**Comment by jchodera** [comment]
Don't forget the tests!  They're in [`repex/repex/tests-nose/test_mcmc.py`](https://github.com/choderalab/repex/blob/master/repex/tests-nose/test_mcmc.py).

I'll enable travis.

**Comment by jchodera** [comment]
Maybe we can put the tests in `mcmcsampler/tests/` instead of calling it `tests-nose/`?

Also, you'll probably want the most up-to-date `devtools/` stuff in here:
https://github.com/omnia-md/devtools

**Comment by jchodera** [comment]
Travis is enabled.

**Comment by pgrinaway** [comment]
Getting the devtools stuff together now.

**Comment by jchodera** [comment]
You'll still need to create `.travis.yml` manually, and tailor it to this repo by replacing the `PACKAGENAME`.

**Comment by jchodera** [comment]
I just remembered why the subrepo idea wouldn't work---the `devtools/conda-recipe/` still needs to be created individually for each package.  Sorry for leading you astray here.

**Comment by pgrinaway** [comment]
No worries. Going to fix this now.

**Comment by jchodera** [comment]
Don't worry about fixing `repex`---I can take care of that.

**Comment by pgrinaway** [comment]
> Don't worry about fixing repex---I can take care of that.

Thanks!

A few questions:

 What should the actual name of this package be? I was thinking `mcmcsampler` might not be good (I just picked something randomly). `openmmmcmcsampler` seems a bit long, with a lot of Ms (I don't know why that weirds me out...). Anyway, if you have a better suggestion I'll change it.

Also, who should the author be in the `setup.py`? You?

Thanks!

**Comment by pgrinaway** [comment]
Looks like there was a typo in the `.travis.yml` that I copy/pasted. Want me to file a PR to the `devtools` repo to fix that readme, or should I just directly commit the change?

**Comment by jchodera** [comment]
> A few questions:
> 
> What should the actual name of this package be? I was thinking
> mcmcsampler might not be good (I just picked something randomly).
> openmmmcmcsampler seems a bit long, with a lot of Ms (I don't know why that
> weirds me out...). Anyway, if you have a better suggestion I'll change it.

Doesn't matter much unless you really don't like the name.
- openmcmc?
- emcee?
- mchammer?

Unless this should go in openmmtools?  Dunno.

> Also, who should the author be in the setup.py? You?

Sure.

**Comment by jchodera** [comment]
> Looks like there was a typo in the .travis.yml that I copy/pasted. Want
> me to file a PR to the devtools repo to fix that readme, or should I just
> directly commit the change?

PR?

**Comment by dwhswenson** [comment]
Re: "emcee" as potential name: http://dan.iel.fm/emcee/current/

**Comment by pgrinaway** [comment]
> Re: "emcee" as potential name: http://dan.iel.fm/emcee/current/

Thanks! I'm just going to stick with the current name. We can refactor later if someone has a serious problem with it.

**Comment by pgrinaway** [comment]
Ok, the tests seem to be running now, but one is failing.

**Comment by jchodera** [comment]
Hm.  Travis isn't running now?

**Comment by jchodera** [comment]
I can fix the broken test if you want to merge, but I'm not sure why travis has died.

**Comment by jchodera** [comment]
I see: repo name changed.  Fixed.  Go ahead and push a new commit to get it to re-run.

**Comment by pgrinaway** [comment]
OH! Sorry, I think I see what you meant. It was actually running, but not being linked to the repo. Sorry!

**Comment by pgrinaway** [comment]
not sure what's going on with the python3 checks...

**Comment by pgrinaway** [comment]
@bas-rustenburg pointed out that `openmoltools-dev` is not being built for python3.

**Comment by bas-rustenburg** [comment]
Or rather, it is only being built for 2.7 and 3.3. Not sure where it's being built. I just checked anaconda.org.

**Comment by pgrinaway** [comment]
Thanks for the clarification!

**Comment by pgrinaway** [comment]
Looks like there are now some legitimate code failures. I think they should be addressed in another PR as discussed with @jchodera a few minutes ago.

**Comment by pgrinaway** [comment]
I think there are also python 3 compatibility issues here.

**Pull request merged**
