### PR TITLE
Fix bug in setting pressure in MD units.

### PR DESCRIPTION
**Pull request by jchodera**
Addresses #3 

There is really only one change here:

```
-            context.setParameter(parameter_name, thermodynamic_state.pressure)
+            context.setParameter(parameter_name, thermodynamic_state.pressure.value_in_unit_system(u.md_unit_system))
```

but Atom has removed all extra trailing spaces.

### CODE REVIEW

**Comment by pgrinaway** [comment]
Ok thanks!

**Comment by pgrinaway** [comment]
Nice! Looks like the Python 2 build is working. I think I found the culprit for the Python 3 build though. In Python 3, I think `dict.keys()` returns a `dictkeys(list_of_keys)` object. `list(dict.keys())` seems to resolve that.

**Comment by pgrinaway** [comment]
So if [here](https://github.com/choderalab/openmmmcmc/blob/master/openmmmcmc/mcmc.py#L569) we had `list(self.move_set.keys())` perhaps that would fix it. [This PEP](https://www.python.org/dev/peps/pep-3106/) suggests that that might be the right approach here.

**Comment by jchodera** [comment]
`list(dict)` is even simpler, I think

**Comment by jchodera** [comment]
Already fixed!

**Comment by pgrinaway** [comment]
oops, too slow! sorry!

**Comment by jchodera** [comment]
Really not sure why the minimization test is timing out.  It should only be testing `AlanineDipeptideVacuum`, which should be fast on all platforms.

**Comment by pgrinaway** [comment]
Doesn't it test all of them [here](https://github.com/choderalab/openmmmcmc/blob/master/tests/test_mcmc.py#L32)?

**Comment by jchodera** [comment]
I changed that:
https://github.com/jchodera/openmmmcmc/blob/master/tests/test_mcmc.py#L31-L33

**Comment by jchodera** [comment]
I am so confused.  Why is `nose` running some of these tests _twice_ and not spitting out any print output?

```
openmmmcmc.tests.test_mcmc.test_doctest ... ok (22.9123s)
openmmmcmc.tests.test_mcmc.test_minimizer_all_testsystems ... ok (535.1079s)
openmmmcmc.tests.test_mcmc.test_mcmc_expectations ... ok (395.8052s)
openmmmcmc.tests.test_mcmc.test_minimizer_all_testsystems: 535.1079s
openmmmcmc.tests.test_mcmc.test_mcmc_expectations: 395.8052s
openmmmcmc.tests.test_mcmc.test_doctest: 22.9123s
```

**Comment by jchodera** [comment]
Something is totally fucked up here.

**Comment by jchodera** [comment]
_facepalm_

There were two sets of nearly-but-not-quite-identical tests:
- `tests/`
- `openmmtools/tests/`

**Comment by jchodera** [comment]
Testing could still be sped up further, but I'll merge now.

**Pull request merged**
